### PR TITLE
St. Olaf streams endpoint

### LINKED ISSUE #59: [endpoint] St. Olaf Multimedia upcoming streams
URL: https://www.stolaf.edu/multimedia/api/collection
Usage: https://github.com/StoDevX/AAO-React-Native/blob/47583bb99fa69c45785330591cc2276fa7a866a5/source/views/streaming/streams/list.js
Types: https://github.com/StoDevX/AAO-React-Native/blob/47583bb99fa69c45785330591cc2276fa7a866a5/source/views/streaming/streams/types.js

Suggested endpoint: `/v1/videos/stolaf`

I'm suggesting a `videos` namespace because `multimedia` or `broadcast-media` just doesn't sound right to me, and I'd like to be able to add … other things? to it. Not that I can come up with anything else, mind. I'd just like to leave the option open.

### PR DESCRIPTION
**Pull request by drewvolz**
Closes #59 

Routes for upcoming as well as archived streams. Can request number of months.

URI | Params | Returns | Default
--|--|--|--
`/v1/streams/upcoming` | (string) `to` date | Upcoming streams up through a `to` date | +2 months
`/v1/streams/archived` | (string) `from` date | Previous streams up until a `from` date | -2 months

### CODE REVIEW

**Comment by hawkrives** [comment]
Can we do dates instead of months, please?

**Comment by hawkrives** [comment]
I will ask that you look into why we call parseHtml in the Streams View in AAO, and how we can move that to the server.

**Comment by hawkrives** [comment]
Oh! Also we should provide a way to disable the "athletics" filtering, because I think we'll want a way to show those when we add the FilterToolbar to the view.

**Comment by drewvolz** [comment]
That’s a good idea. After that, how much of the spec should we pack into this PR? Pagination, lookup by id, search by title/performer/location/length, etc

**Comment by hawkrives** [comment]
I think this PR is fine to only support the date parameters. We can file an issue for passing more stuff through later.

**Comment by drewvolz** [comment]
For what it's worth, here's a list of some previous `performers` and `subtitle` fields from both BMS and FP APIs.

<details>
<summary>BMS performers and subtitles</summary>

```json
"Conference on Worship, Theology, and the Arts<br />Creating, Provoking, Empowering Spirit",
"Conference on Worship, Theology, and the Arts<br />Empowering Spirit",
"Conference on Worship, Theology, and the Arts",
"Conference on Worship, Theology, and the Arts<br />Provoking Spirit",
"Conference on Worship, Theology, and the Arts",
"Conference on Worship, Theology, and the Arts<br />Creating Spirit",
"Conference on Worship, Theology, and the Arts",
"Conference on Worship, Theology, and the Arts<br />Creating, Provoking, Empowering Spirit",
"TCAGO Pipe Organ Encounter Recital",
"TCAGO Pipe Organ Encounter Recital",
"St. Olaf Summer Music Academy",
"Reunion Weekend: All Alumni Worship",
"Reunion Weekend: Holden Evening Prayer",
"Reunion Weekend: A CUBE Retrospective",
"Reunion Weekend: All-Alumni Celebration",
"Reunion Weekend: Class of 1968 Service of Remembrance",
"Reunion Weekend: Chapel Service",
"Commencement Ceremony",
"Baccalaureate Service: Holy Trinity Sunday",
"Campus Illumination Ceremony & Lighting",
"Commencement Weekend Concert",
"Last Lecture for the Class of 2018",
"A Service of Sending",
"Daily Chapel",
"Daily Chapel",
"Senior Soloists Concert",
"Seventh Sunday of Easter",
"Gospel Choir of St. Olaf",
"Service of Morning Prayer",
"Daily Chapel",
"Daily Chapel",
"Turning Point USA Student Organization Speaker",
"Daily Chapel",
"Daily Chapel",
"St. Olaf Baseball",
"St. Olaf Baseball",
"Sixth Sunday of Easter",
"Jazz I",
"2018 Ole Cup: Business Pitches & Student Presentations",
"Political Awareness Committee Student Organization Speaker",
"Honors Day Convocation",
"Honors Day Convocation",
"Jazz II & III",
"Daily Chapel",
"St. Olaf Softball",
"St. Olaf Softball",
"Daily Chapel",
"St. Olaf Baseball",
"St. Olaf Baseball",
"Daily Chapel",
"St. Olaf Choir",
"Anna Odegaard<br />Health Policy Analyst at SEIU Healthcare Minnesota",
"International Contemporary Ensemble",
"International Contemporary Ensemble",
"Michael Oakes Ph.D., Associate Professor, University of Minnesota & Co-Director, US Census Data Research Center",
"Timothy Holtz '86<br />Director, HIV/STD Research Program; Thailand Ministry of Public Health - US CDC Collaboration, Thailand",
"James Bobb, Cantor to the Student Congregation",
"Matthew Marohl, College Pastor",
"Matthew Marohl, College Pastor",
"The Miami University Men's Glee Club - Dr. Jeremy Jones, Conductor",
"Ruth Neuger, Women's Softball Coach, Assistant Soccer Coach & Senior Admissions Officer",
"Dan Dressen, Brian Link, James Bohn & Philip Brunelle, Guest Artists",
"Matthew Marohl, College Pastor",
"Kurt Anderson, Head Men's Soccer Coach & Assistant Baseball Coach",
"Charlie Ruud '04, Associate Pastor, Bethel Lutheran Church, Northfield",
"John Gorder '67, Acting Associate College Pastor",
"Will Healy, Senior Pastor, Emmaus Church, Northfield, Minnesota",
"Matthew Marohl, College Pastor",
"Rev. Kelly Chatman, Redeemer Lutheran Church, Minneapolis",
"Michon Weeks, Assistant Professor of Art",
"David Olson '91, Assistant Men's Tennis Coach",
"St. Olaf Orchestra Strings - Steven Amundson, Conductor",
"John Gorder '67, Acting Associate College Pastor",
"Timothy McDermott, Senior Pastor, Bethel Lutheran Church, Northfield",
"Ethan Smith '13,  Eden Prairie, Minnesota",
"Chris Folken '14 and Caitlyn Owsley '14",
"Matthew Marohl, College Pastor",
"Hosted by Melissa Ousley",
"Mary Cisar, Registrar and Assistant Vice-president for Academic Affairs",
"Jennifer Arnspong '13, Northbrook, Illinois",
"John Gorder '67, Acting Associate College Pastor",
"Matthew Marohl, College Pastor",
"Joan Hepburn, Assistant Professor of English<br />Lakresha Williams '15, Hopkins, Minn.",
"John Gorder '67, Acting Associate College Pastor",
"Hosted by Melissa Ousley",
"Tom Williamson, Associate Professor of Anthropology",
"Mary Anderson, Visiting Assistant Professor of Religion",
"\"The Minnesota Health Insurance Exchange: An Inside Look\"",
"Matthew Marohl, College Pastor",
"Kathleen Shea, Professor of Biology and Curator of Natural Lands",
"John Gorder '67, Acting Associate College Pastor",
"\"The Social Determinants of Health: Past, Present, Future\"",
"\"Social Inequalities and HIV in Asia: The Search for New Prevention Methods\"",
"Matthew Marohl, College Pastor",
" Amy Chatelaine '12, Discipleship Year Intern",
"Paul Drees '13, Katy, Texas",
"John Gorder '67, Acting Associate College Pastor",
"Iowa State University Singers<br />Dr. James Rodde, conductor"
```

</details>

<details>
<summary>FP performers and subtitles</summary>

```json
"Hymns for Christmastide",
"Service of Morning Prayer for the Epiphany Season",
"Epiphany of Our Lord",
"Daily Chapel",
"Daily Chapel",
"Daily Chapel",
"Benjamin Britten - Canticle IV, \"Journey of the Magi\"",
"Service of Morning Prayer for the Epiphany Season",
"Baptism of Our Lord",
"Daily Chapel",
"Daily Chapel",
"Daily Chapel",
"Daily Chapel",
"Service of Morning Prayer for the Epiphany Season",
"Second Sunday after Epiphany - Lectionary 2",
"Martin Luther King Jr. Day",
"Daily Chapel",
"Daily Chapel",
"\"Musica Celestis\" by Aaron Jay Kernis",
"Service of Morning Prayer for the Epiphany Season",
"Third Sunday after Epiphany - Lectionary 3",
"Daily Chapel",
"Daily Chapel",
"Daily Chapel",
"Service of Morning Prayer for the Epiphany Season",
"Transfiguration of Our Lord",
"Winter Tour Home Concert",
"Daily Chapel",
"Daily Chapel",
"Ash Wednesday: Burning of the Palm Branches",
"Ash Wednesday: Evening Service",
"Black History Month Observance",
"Service of Morning Prayer for Lent",
"First Sunday in Lent",
"Winter Tour Home Concert",
"Daily Chapel",
"Daily Chapel",
"2013 Social Science Conference",
"Lenten Series I:<br />\"The Word Became Flesh and Dwelled Among Us\"",
"Guest Recital",
"Daily Chapel",
"Guest Recital",
"Service of Morning Prayer for Lent",
"2013 Social Science Conference",
"2013 Social Science Conference",
"Second Sunday in Lent",
"Daily Chapel",
"Daily Chapel",
"Lenten Series II:<br />\"The Word Became Flesh and Dwelled Among Us\"",
"Daily Chapel"
"Donald E. Saliers",
"Dee McIntosh, Lead Pastor, LightHouse Covenant Church",
"Recital",
"Jer Swigart",
"Northfield Noontime Organ Recital Series",
"Donald E. Saliers",
"Recital",
"Matthew Marohl, College Pastor</br>Katherine Fick, Associate College Pastor",
"Johann Sebastian Bach: Master Craftsman",
"Hymn Sing and Silent Movie",
"Ensemble Concert",
"Matthew Marohl, College Pastor",
"50 years of the Cultural Union for Black Expression",
"A. Malcolm (Mac) Gimse '58, Professor Emeritus of Art<br />Field Supervisor for Global Semester",
"St. Olaf Class of 2018",
"Katherine E. Fick, Preacher",
"In Search of Our Mothers’ Gardens on the Hill",
"Jeff Dixon, Project Programmer, IT",
"Matthew Damhof '18, Clearwater, Minnesota",
"Matthew Marohl, College Pastor",
"\"Because of Love\"",
"Marit McQuaig '18, Wenatchee, Washington",
"Jack Goldstein '18, Plymouth, Minnesota",
"Abigail Stets '18, Northfield, Minnesota",
"Jacqueline Hanson '18, West Saint Paul, Minnesota",
"vs. Saint Mary's University",
"vs. Saint Mary's University",
"Katherine Fick, Associate College Pastor",
"Meg Ojala, Professor of Art/Art History<br />John Barbour, Professor of Religion",
"Bishop Alex Mkumbo, Central Diocese of Tanzania",
"vs. Bethel University",
"vs. Bethel University",
"Collegiate Chorale - Anton Armstrong '78, Conductor",
"vs. Gustavus Adolphus College",
"vs. Gustavus Adolphus College",
"Andy Jacob '18, Edina, Minnesota",
"James E. Bobb, Organ<br />Martin Hodel, Trumpet",
"Catherine Rodland, St. Olaf College",
"Students from the International Cello Institute",
"Christopher Jacobson '03, Organ",
"Catherine Rodland '87, Organ<br />James Bobb, Organ<br />John Ferguson, Organ",
"Orchestra, Steven Amundson, Conductor<br />Choir, Therees Tkach Hibbard, Conductor<br />Band, Timothy Mahr '78, Conductor",
"with President David R. Anderson '74",
"St. Olaf Band & St. Olaf Choir",
"Class of 2018",
"St. Olaf Orchestra<br />St. Olaf Choir<br />St. Olaf Band",
"Jennifer Kwon Dobbs, Associate Professor of English, Director of Race and Ethnic Studies",
"St. Olaf Orchestra & Senior Soloists",
"Paulo Gladney '18, Music Director<br />Kaci Campbell '19, Assistant Music Director",
"Candace Owens",
"Jazz I",
"Noam Chomsky",
"Meg Ojala, Professor of Art/Art History<br />John Barbour, Professor of Religion",
"Jazz II & III",
```

</details>

**Pull request merged**
