### PR TITLE
Update mess news endpoint

### PR DESCRIPTION
**Pull request by drewvolz**
The old endpoint is not responding

### CODE REVIEW

**Review by hawkrives — APPROVED** [review]

**Comment by hawkrives** [comment]
Looks like the redirect is HTTP-only for some reason, and the HTTPS cert doesn't match

```
Last login: Thu Oct  8 11:22:01 on ttys010
Welcome to fish, the friendly interactive shell
~$ curl 'https://www.manitoumessenger.com/wp-json/wp/v2/posts/'
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
~$ curl 'http://www.manitoumessenger.com/wp-json/wp/v2/posts/'
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://www.theolafmessenger.com/wp-json/wp/v2/posts/">here</a>.</p>
</body></html>
```

**Review by rye — APPROVED** [review]
Re-ran the build due to some weird build failures.

We might also want to `s/manitou/theolaf/g` in other places too…

I can deploy at lunch.

**Comment by drewvolz** [comment]
Still getting odd errors... should we merge regardless?

**Comment by rye** [comment]
I just reran one more time and it failed. Might be worth [giving this a try](https://discuss.circleci.com/t/docker-build-fails-with-nonsensical-eperm-operation-not-permitted-copyfile/37364) (i.e. change our CircleCI node version to 12, which would also match our Dockerfile version too)

**Comment by drewvolz** [comment]
@dependabot rebase

**Comment by rye** [comment]
Dependabot doesn't seem to rebase PRs it didn't author.

I rebased (and squashed the annihilating commits) and just pushed.

**Review by rye — APPROVED** [review]

**Comment by drewvolz** [comment]
Thanks, Kris!

**Pull request merged**
