### PR TITLE
Bon-App nutrition endpoint for stolaf and carleton

### PR DESCRIPTION
**Pull request by drewvolz**
```bash
$ > https://stolaf.api.frogpond.tech/v1/food/item/10429171
$ > https://carleton.api.frogpond.tech/v1/food/item/10429172
```

<details>
<summary>One with vendors and cor-icons</summary>

```json
{
   "items":{
      "10429171":{
         "id":"10429171",
         "label":"roast petit pan yellow squash and carrots",
         "description":"st. olaf campus farm (stogrow)",
         "zero_entree":"0",
         "raw_cooked":"0",
         "cor_icon":{
            "6":"Farm to Fork"
         },
         "price":"",
         "sizes":[

         ],
         "nutrition_summary":{
            "kcal":"",
            "well_being":"",
            "well_being_image":""
         },
         "nutrition_details":{

         },
         "ingredients":"",
         "ingredient_details":"",
         "nutrition_info":"",
         "special":1,
         "rating":"",
         "connector":"",
         "options":[

         ],
         "vendors":[
            {
               "id":"1411",
               "name":"st. olaf campus farm (stogrow)",
               "location":"northfield, mn",
               "city":"northfield",
               "state":"mn",
               "distance":"1.1 mi",
               "url":"stogrowfarm.wordpress.com",
               "image":"https://legacy.cafebonappetit.com/assets/vendors/1411-c2ea59a9f3403e8def7ba96fc911edcd.jpg",
               "products":"seasonal availability"
            }
         ],
         "monotony":{

         }
      }
   },
   "cor_icons":{
      "6":{
         "label":"Farm to Fork",
         "description":"Farm to Fork: Contains seasonal, minimally processed ingredients from a local farm, ranch, or fishing boat.",
         "image":"https://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-d58f59.png?v=1528869690",
         "is_filter":"N",
         "allergen":0,
         "type":"diet"
      }
   },
   "vendors":{
      "1411":{
         "id":"1411",
         "name":"st. olaf campus farm (stogrow)",
         "location":"northfield, mn",
         "city":"northfield",
         "state":"mn",
         "distance":"1.1 mi",
         "url":"stogrowfarm.wordpress.com",
         "image":"https://legacy.cafebonappetit.com/assets/vendors/1411-c2ea59a9f3403e8def7ba96fc911edcd.jpg",
         "products":"seasonal availability"
      }
   },
   "reviews":{

   }
}
```

</details>

<details>
<summary>One with nutritional info</summary>

```json
{
   "items":{
      "10429172":{
         "id":"10429172",
         "label":"cheddar twice baked potatoes",
         "description":"",
         "zero_entree":"0",
         "raw_cooked":"0",
         "cor_icon":{
            "1":"Vegetarian",
            "9":"Made without Gluten-Containing Ingredients"
         },
         "price":"",
         "sizes":[

         ],
         "nutrition_summary":{
            "kcal":"",
            "well_being":"",
            "well_being_image":""
         },
         "nutrition_details":{
            "calories":{
               "label":"Calories",
               "value":"140",
               "unit":""
            },
            "servingSize":{
               "label":"Serving Size",
               "value":"4.0",
               "unit":"oz"
            },
            "fatContent":{
               "label":"Total Fat",
               "value":"4.5",
               "unit":"g"
            },
            "saturatedFatContent":{
               "label":"Saturated Fat",
               "value":"2.5",
               "unit":"g"
            },
            "transFatContent":{
               "label":"Trans Fat",
               "value":"0",
               "unit":"g"
            },
            "cholesterolContent":{
               "label":"Cholesterol",
               "value":"10",
               "unit":"mg"
            },
            "sodiumContent":{
               "label":"Sodium",
               "value":"75",
               "unit":"mg"
            },
            "carbohydrateContent":{
               "label":"Total Carbohydrate",
               "value":"22",
               "unit":"g"
            },
            "fiberContent":{
               "label":"Dietary Fiber",
               "value":"1",
               "unit":"g"
            },
            "sugarContent":{
               "label":"Sugars",
               "value":"2",
               "unit":"g"
            },
            "proteinContent":{
               "label":"Protein",
               "value":"4",
               "unit":"g"
            }
         },
         "ingredients":"",
         "ingredient_details":"",
         "nutrition_info":"            <div class='menu-item-nutrition'>\n                <h4 class='food-item-name'>Nutrition Information:</h4>\n                    <h4 class='food-item-name modal-title'>cheddar twice baked potatoes</h4>\n        <div style='font-weight: bold;' class='menu-item-serving-size' data-portion='4.0'><span>Serving Size:</span> 4.0 oz.</div>\n        <table class='eni-menu-facts' onselectstart='return false;' onmousedown='return false;' oncopy='return false;'>\n                \n                <tr>\n                                            <td class='fdaSection-0'>Calories</td>\n                <td>140</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-0'>Sodium</td>\n                <td>75mg</td>\n            \n        </tr>\n                <tr>\n                                            <td class='fdaSection-0'>Total Fat</td>\n                <td>4.5g</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-0'>Total Carbohydrate</td>\n                <td>22g</td>\n            \n        </tr>\n                <tr>\n                                            <td class='fdaSection-1'>Saturated Fat</td>\n                <td>2.5g</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-1'>Dietary Fiber</td>\n                <td>1g</td>\n            \n        </tr>\n                <tr>\n                                            <td class='fdaSection-1'>Trans Fat</td>\n                <td>0g</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-1'>Sugars</td>\n                <td>2g</td>\n            \n        </tr>\n                <tr>\n                                            <td class='fdaSection-0'>Cholesterol</td>\n                <td>10mg</td>\n            \n                                            <td class='eni-facts-column2 fdaSection-0'>Protein</td>\n                <td>4g</td>\n            \n        </tr>\n            </table>\n<div class='disclaimer'>\n    <p><span class='asterisk'>*</span> We attempt to provide nutrition information that is as complete as possible. The nutritional values are based on standard product formulations, data from our suppliers, and are based on the specified portion size. Variations may occur due to the use of regional suppliers, seasonal influences, differences in product preparation at the unit level, and recipe revisions. Nutrient values are rounded according to FDA Rounding Rules. For your convenience at self-serve station, we have provided utensils that will help you approximate the specified portion.</p>\n</div>                    ",
         "special":1,
         "rating":"",
         "connector":"",
         "options":[

         ],
         "vendors":[

         ],
         "monotony":{

         }
      }
   },
   "cor_icons":{
      "1":{
         "label":"Vegetarian",
         "description":"Vegetarian: Contains no meat, fish, poultry, shellfish or products derived from these sources but may contain dairy or eggs",
         "image":"https://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-c9d18b.png?v=1528869517",
         "is_filter":"Y",
         "allergen":0,
         "type":"diet"
      },
      "9":{
         "label":"Made without Gluten-Containing Ingredients",
         "description":"Made without Gluten-Containing Ingredients: does not contain ingredients that are sources of gluten, but is prepared in an open kitchen where gluten is present.",
         "image":"https://legacy.cafebonappetit.com/assets/cor_icons/menu-item-type-ce9d00.png?v=1528869625",
         "is_filter":"Y",
         "allergen":0,
         "type":"diet"
      }
   },
   "vendors":{

   },
   "reviews":{

   }
}
```

</details>

### CODE REVIEW

**Comment by drewvolz** [comment]
The `menu` api call currently provides nutritional information. I think this gets us a few more props, but it depends in what we're after.

**Comment by hawkrives** [comment]
Can you check that this gets us additional information, please? I'd love to see exactly what extra stuff we get.

**Comment by drewvolz** [comment]
Looks like you gain:
* cor_icon description
* vendors
* reviews
* nutrition_info html table

...so not a whole lot.

**Comment by hawkrives** [comment]
I'm fine with merging this, but it sounds like we may never make use of it, if that's all it gets us. It's really nice to not have to make a new request when you open a detail view, imo.

but if you want to show something from that request, go ahead; we can start out with the known data and enhance with the remote data once it's loaded.

**Comment by drewvolz** [comment]
I don’t think I’d ever care to see the vendors or review I’m happy with the occasional nutritional facts that are provided to the non-specials. I’m in favor of closing this and coming back if we change our minds. I agree with you. It’s not worth the separate network call when 95% of the props were provided from the first fetch.

**Comment by rye** [comment]
This is ccc-server, where we are just proxying network requests, no? If AAO doesn't use them, AAO doesn't use them. Still nice to have in the API.

**Comment by drewvolz** [comment]
If both @hawkrives and @rye are okay with including this and not using it, then it sounds good to me.

**Pull request merged**
